
from django.urls import path
from  .views import *
urlpatterns = [
      path('admin-login/',admin_login_api), 
      path('add-category/',add_category),
      path('categories/',list_categories),
      path('foods/',list_foods),
      path('add-food-item/',add_food_item),
      path('food_search/',food_search),
      path('random_foods/',random_foods),
      path('register/',register_user),
      path('login/',login_user),
      path('foods/<int:id>/',food_detail),
      path('cart/add/',add_to_cart),
      path('cart/<int:user_id>/',get_cart_items),
      path('cart/update_quantity/',update_cart_quantity),
      path('cart/delete/<int:order_id>/',delete_cart_item),
      path('place_order/',place_order),
      path('orders/<int:user_id>/',user_orders),
      path('orders/by_order_number/<str:order_number>/',order_by_order_number),
      path('orders/order_address/<str:order_number>/',get_order_address),
      path('invoice/<str:order_number>/',get_invoice),
      path('user/<int:user_id>/',get_user_profile),
      path('user_update/<int:user_id>/',update_user_profile),
      path('change_password/<int:user_id>/',change_password),
      path('orders-not-confirmed/',orders_not_confirmed),
      path('orders-confirmed/',orders_not_confirmed),
      path('foodpickup/',food_pickup),
      path('food_being_prepared/',food_being_prepared),
      path('food-delivered/',food_delivered),
      path('food-cancelled/',food_cancelled),
      path('all-orders/',all_orders),
      path('order-between-dates/',order_between_dates),
      path('view-order-detail/<str:order_number>/',view_order_detail),
      path('update-order-status/',update_order_status),
      path('search-orders/',search_order),
      path('category/<int:id>/',category_detail),
      path('delete-food/<int:id>/',delete_food),
      path('edit-food/<int:id>/',edit_food),
      path('users/',list_users),
      path('delete_user/<int:id>/',delete_user),
      path('dashboard_metrics/',dashboard_metrics),
      path('monthly_sales_summary/',monthly_sales_summary),
]

