# Generated by Django 5.2.9 on 2026-01-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
